version: "3.4"

services:
  build:
    build:
      dockerfile: docker/build/Dockerfile
      context: .
    user: "1000:1000"
    restart: "no"
    volumes:
      - ./bin:/go/src/github.com/TrueGameover/transaq-grpc/bin
    networks:
      default:
        ipv4_address: 192.168.65.2

  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
      target: final
    restart: "no"
    ports:
      - "192.168.65.1:50051:50051"
    volumes:
      - ./bin/logs:/go/src/github.com/TrueGameover/transaq-grpc/bin/logs
    networks:
      default:
        ipv4_address: 192.168.65.3

  debug:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
      target: debug_prod
    restart: "no"
    ports:
      - "192.168.65.1:50051:50051"
    volumes:
      - ./bin/logs:/go/src/github.com/TrueGameover/transaq-grpc/bin/logs
    networks:
      default:
        ipv4_address: 192.168.65.4

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.65.0/24
